version: "3"

services:
  web:
    build: .
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - POSTGRES_CONN=user=user password=password host=db port=5432 dbname=prod_proj_db sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - ../tests:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=prod_proj_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
