version: "3"

services:
  web:
    build: .
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - POSTGRES_CONN=postgres://user:password@db:5432/prod_proj_db
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - ../tests:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=prod_proj_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - 5050:80

volumes:
  pgadmin_data:
